name: kamera
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Plugin yang kamu gunakan
  camera: ^0.10.0+2
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2
  path_provider: ^2.1.3

  # Icon iOS (Cupertino)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  # Gunakan material design icons
  uses-material-design: true

  # Aktifkan assets jika kamu punya gambar
  # Contoh: folder `assets/images/` harus ada di proyek
  # assets:
  #   - assets/images/
